### PR TITLE
Development

### PR DESCRIPTION
**Pull request by mcrd25**

### CODE REVIEW

**Review by heyapricot — CHANGES_REQUESTED** [review]
# Am I seeing triple? 3️⃣
Why are there three versions of the enumerables file? Pick just one of the imlementations and that's the one I'll review.
I like that you decided to add tests to the methods. However, we favor the use of RSpec as a test suite. Please rewrite your tests using rspec. Feel free to reach over crisp if you have any questions. Thanks!

**Comment by mcrd25** [comment]
Hi, we mentioned which in the form. We will do it in RSPEC but have not
reached that section yet. I believe that is for the project in RSPEC.

Would yiu require us to do it in RSPEC for us to submit it?

**Comment by mcrd25** [comment]
The correct one is the my_enumerables.rb the regularly named file. Is it
possible to review it as is?

**Comment by adriaanbd** [comment]
> # Am I seeing triple? three
> 
> Why are there three versions of the enumerables file? Pick just one of the imlementations and that's the one I'll review.
> I like that you decided to add tests to the methods. However, we favor the use of RSpec as a test suite. Please rewrite your tests using rspec. Feel free to reach over crisp if you have any questions. Thanks!

Hi Alvaro, we've removed the additional files. You can go ahead and review as is, or wait until we submit the Rspec tests for this project.

**Comment by heyapricot** [comment]
# Looking good 😎 Got a little hiccup 🥴
👋🏼 Hello! The implementation is sharp, original and efficient. However, i found a little detail
`b = [1,2,3,4,5]`
`b.inject {|acc, val| acc + val }` results in `15`
`b.my_inject {|acc, val| acc + val }` results in `16`

Please take a look at that. Thanks :)

**Comment by adriaanbd** [comment]
> # Looking good sunglasses Got a little hiccup 🥴
> 
> 👋🏼 Hello! The implementation is sharp, original and efficient. However, i found a little detail
> `b = [1,2,3,4,5]`
> `b.inject {|acc, val| acc + val }` results in `15`
> `b.my_inject {|acc, val| acc + val }` results in `16`
> 
> Please take a look at that. Thanks :)

Hi Alvaro, thanks for catching that! We've done the corrections, please take a look and lets us know what you think.

**Review by heyapricot — APPROVED** [review]
# Problem solved ➕
Very nice work team! This is very polished. I like it a lot 😁
No need from my side for further review. Let's move on to the next project 🚀

**Comment by mcrd25** [comment]
Yay! Thanks A lot. ☺

**Pull request merged**
